# Generated by Django 2.0.3 on 2018-04-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=15)),
                ('app_name', models.CharField(max_length=50)),
                ('have_data', models.CharField(default='1', max_length=2)),
                ('app_category', models.CharField(max_length=50, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(blank=True, null=True)),
                ('review_version', models.CharField(max_length=20)),
                ('review_rating', models.CharField(max_length=2)),
                ('review_title', models.TextField(blank=True, null=True)),
                ('review_split', models.CharField(default='1', max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('review_app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.App')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='SplitWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.ReviewsContent')),
                ('word_app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.App')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('app_id', 'app_name')},
        ),
    ]
