# Generated by Django 2.0.3 on 2018-04-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='have_data',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='reviewscontent',
            name='review_split',
            field=models.CharField(max_length=2),
        ),
    ]
