# Generated by Django 2.0.3 on 2018-04-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180419_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitwords',
            name='content_id',
        ),
    ]
